# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\scku\Desktop\GitRepos\STARBME\starbme_src\gui\ui\ui_BmeEstDlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets

def _fromUtf8(s):
    return s

def _translate(context, text, disambig):
    return QtCore.QCoreApplication.translate(context, text)

class Ui_BmeEstDlg(object):
    def setupUi(self, BmeEstDlg):
        BmeEstDlg.setObjectName(_fromUtf8("BmeEstDlg"))
        BmeEstDlg.resize(316, 214)
        self.verticalLayout = QtWidgets.QVBoxLayout(BmeEstDlg)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtWidgets.QTabWidget(BmeEstDlg)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.comboBox_order = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_order.sizePolicy().hasHeightForWidth())
        self.comboBox_order.setSizePolicy(sizePolicy)
        self.comboBox_order.setObjectName(_fromUtf8("comboBox_order"))
        self.comboBox_order.addItem(_fromUtf8(""))
        self.comboBox_order.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBox_order)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_47 = QtWidgets.QLabel(self.tab)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_3.addWidget(self.label_47)
        self.lineEdit_spatialrange = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_spatialrange.setText(_fromUtf8(""))
        self.lineEdit_spatialrange.setObjectName(_fromUtf8("lineEdit_spatialrange"))
        self.horizontalLayout_3.addWidget(self.lineEdit_spatialrange)
        self.label_46 = QtWidgets.QLabel(self.tab)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.horizontalLayout_3.addWidget(self.label_46)
        self.lineEdit_temporalrange = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_temporalrange.setText(_fromUtf8(""))
        self.lineEdit_temporalrange.setObjectName(_fromUtf8("lineEdit_temporalrange"))
        self.horizontalLayout_3.addWidget(self.lineEdit_temporalrange)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_45 = QtWidgets.QLabel(self.tab)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.horizontalLayout_5.addWidget(self.label_45)
        self.lineEdit_stratio = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_stratio.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_stratio.setText(_fromUtf8(""))
        self.lineEdit_stratio.setObjectName(_fromUtf8("lineEdit_stratio"))
        self.horizontalLayout_5.addWidget(self.lineEdit_stratio)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_43 = QtWidgets.QLabel(self.tab)
        self.label_43.setMinimumSize(QtCore.QSize(35, 16))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.horizontalLayout_2.addWidget(self.label_43)
        self.lineEdit_nhmax = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_nhmax.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_nhmax.setText(_fromUtf8(""))
        self.lineEdit_nhmax.setObjectName(_fromUtf8("lineEdit_nhmax"))
        self.horizontalLayout_2.addWidget(self.lineEdit_nhmax)
        self.label_44 = QtWidgets.QLabel(self.tab)
        self.label_44.setMinimumSize(QtCore.QSize(35, 16))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_2.addWidget(self.label_44)
        self.lineEdit_nsmax = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_nsmax.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_nsmax.setText(_fromUtf8(""))
        self.lineEdit_nsmax.setObjectName(_fromUtf8("lineEdit_nsmax"))
        self.horizontalLayout_2.addWidget(self.lineEdit_nsmax)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.comboBox_worker_n = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_worker_n.setObjectName(_fromUtf8("comboBox_worker_n"))
        self.horizontalLayout_4.addWidget(self.comboBox_worker_n)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.lineEdit_max_eval_num = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_max_eval_num.setObjectName(_fromUtf8("lineEdit_max_eval_num"))
        self.horizontalLayout_7.addWidget(self.lineEdit_max_eval_num)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_8.addWidget(self.label_4)
        self.lineEdit_rel_err = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_rel_err.setObjectName(_fromUtf8("lineEdit_rel_err"))
        self.horizontalLayout_8.addWidget(self.lineEdit_rel_err)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.checkBox_fast_approx = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_fast_approx.setObjectName(_fromUtf8("checkBox_fast_approx"))
        self.verticalLayout_3.addWidget(self.checkBox_fast_approx)
        self.horizontalLayout_pca = QtWidgets.QHBoxLayout()
        self.horizontalLayout_pca.setObjectName(_fromUtf8("horizontalLayout_pca"))
        self.label_pca = QtWidgets.QLabel(self.tab_2)
        self.label_pca.setObjectName(_fromUtf8("label_pca"))
        self.horizontalLayout_pca.addWidget(self.label_pca)
        self.lineEdit_pca_threshold = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_pca_threshold.setObjectName(_fromUtf8("lineEdit_pca_threshold"))
        self.horizontalLayout_pca.addWidget(self.lineEdit_pca_threshold)
        self.verticalLayout_3.addLayout(self.horizontalLayout_pca)
        self.checkBox_nonneg = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_nonneg.setObjectName(_fromUtf8("checkBox_nonneg"))
        self.verticalLayout_3.addWidget(self.checkBox_nonneg)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.line_2 = QtWidgets.QFrame(BmeEstDlg)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton_estimate = QtWidgets.QPushButton(BmeEstDlg)
        self.pushButton_estimate.setObjectName(_fromUtf8("pushButton_estimate"))
        self.horizontalLayout.addWidget(self.pushButton_estimate)
        self.pushButton_cancel = QtWidgets.QPushButton(BmeEstDlg)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(BmeEstDlg)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BmeEstDlg)

    def retranslateUi(self, BmeEstDlg):
        BmeEstDlg.setWindowTitle(_translate("BmeEstDlg", "Prediction", None))
        self.label_2.setText(_translate("BmeEstDlg", "Order:", None))
        self.comboBox_order.setItemText(0, _translate("BmeEstDlg", "Zero Mean", None))
        self.comboBox_order.setItemText(1, _translate("BmeEstDlg", "Constant Mean", None))
        self.label_47.setText(_translate("BmeEstDlg", "Spatial Range:", None))
        self.label_46.setText(_translate("BmeEstDlg", "Temporal Range:", None))
        self.label_45.setText(_translate("BmeEstDlg", "Spatial/Temporal Ratio:", None))
        self.label_43.setText(_translate("BmeEstDlg", "nhmax:", None))
        self.label_44.setText(_translate("BmeEstDlg", "nsmax:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("BmeEstDlg", "Parameters", None))
        self.label.setToolTip(_translate("BmeEstDlg", "How many CPU you want to process.", None))
        self.label.setText(_translate("BmeEstDlg", "Worker Count:", None))
        self.label_3.setToolTip(_translate("BmeEstDlg", "Maximum number of evaluation of the integral", None))
        self.label_3.setText(_translate("BmeEstDlg", "MaxEvalNum", None))
        self.label_4.setToolTip(_translate("BmeEstDlg", "Relative error on the estimation of the integral", None))
        self.label_4.setText(_translate("BmeEstDlg", "RelErr", None))
        self.checkBox_fast_approx.setToolTip(_translate("BmeEstDlg",
            "Approximate non-Gaussian soft data as Gaussian (mean+variance) "
            "to skip expensive QMC integration. Much faster but slightly less accurate.", None))
        self.checkBox_fast_approx.setText(_translate("BmeEstDlg", "Fast Gaussian Approximation (skip QMC for soft data)", None))
        self.label_pca.setToolTip(_translate("BmeEstDlg",
            "PCA dimension reduction for QMC integration. Keep only principal "
            "components that cumulatively explain this fraction of the total "
            "variance in the conditional covariance. Lower values reduce "
            "dimensionality more aggressively (faster but less accurate). "
            "Set to 1.0 to disable PCA truncation.", None))
        self.label_pca.setText(_translate("BmeEstDlg", "PCA Variance Threshold:", None))
        self.lineEdit_pca_threshold.setToolTip(_translate("BmeEstDlg",
            "Fraction of variance to retain (0.9 to 1.0). Default: 0.999", None))
        self.checkBox_nonneg.setToolTip(_translate("BmeEstDlg",
            "Enforce non-negative estimates. When checked, any estimation "
            "point whose posterior mean is negative will be corrected using "
            "truncated-normal theory so the result is always >= 0. "
            "Recommended for physically non-negative variables "
            "(e.g. concentration, precipitation).", None))
        self.checkBox_nonneg.setText(_translate("BmeEstDlg",
            "Enforce Non-Negative Estimates", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("BmeEstDlg", "Configures", None))
        self.pushButton_estimate.setText(_translate("BmeEstDlg", "Begin", None))
        self.pushButton_cancel.setText(_translate("BmeEstDlg", "Cancel", None))

