# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\scku\Desktop\GitRepos\STARBME\starbme_src\gui\ui\ui_CrossValidationDlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets

def _fromUtf8(s):
    return s

def _translate(context, text, disambig):
    return QtCore.QCoreApplication.translate(context, text)

class Ui_CrossValidationDlg(object):
    def setupUi(self, CrossValidationDlg):
        CrossValidationDlg.setObjectName(_fromUtf8("CrossValidationDlg"))
        CrossValidationDlg.resize(423, 195)
        self.verticalLayout = QtWidgets.QVBoxLayout(CrossValidationDlg)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_9 = QtWidgets.QLabel(CrossValidationDlg)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButton_hard = QtWidgets.QRadioButton(CrossValidationDlg)
        self.radioButton_hard.setChecked(True)
        self.radioButton_hard.setObjectName(_fromUtf8("radioButton_hard"))
        self.buttonGroup = QtWidgets.QButtonGroup(CrossValidationDlg)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton_hard)
        self.horizontalLayout.addWidget(self.radioButton_hard)
        self.radioButton_soft = QtWidgets.QRadioButton(CrossValidationDlg)
        self.radioButton_soft.setObjectName(_fromUtf8("radioButton_soft"))
        self.buttonGroup.addButton(self.radioButton_soft)
        self.horizontalLayout.addWidget(self.radioButton_soft)
        self.radioButton_both = QtWidgets.QRadioButton(CrossValidationDlg)
        self.radioButton_both.setObjectName(_fromUtf8("radioButton_both"))
        self.buttonGroup.addButton(self.radioButton_both)
        self.horizontalLayout.addWidget(self.radioButton_both)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtWidgets.QLabel(CrossValidationDlg)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.spinBox = QtWidgets.QSpinBox(CrossValidationDlg)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(99)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.label_n = QtWidgets.QLabel(CrossValidationDlg)
        self.label_n.setObjectName(_fromUtf8("label_n"))
        self.horizontalLayout_2.addWidget(self.label_n)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        # ---- Worker count row ----
        self.horizontalLayout_workers = QtWidgets.QHBoxLayout()
        self.horizontalLayout_workers.setObjectName(_fromUtf8("horizontalLayout_workers"))
        self.label_workers = QtWidgets.QLabel(CrossValidationDlg)
        self.label_workers.setObjectName(_fromUtf8("label_workers"))
        self.horizontalLayout_workers.addWidget(self.label_workers)
        self.comboBox_worker_n = QtWidgets.QComboBox(CrossValidationDlg)
        self.comboBox_worker_n.setObjectName(_fromUtf8("comboBox_worker_n"))
        self.horizontalLayout_workers.addWidget(self.comboBox_worker_n)
        spacerItem_workers = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_workers.addItem(spacerItem_workers)
        self.verticalLayout.addLayout(self.horizontalLayout_workers)
        self.groupBox_boundary = QtWidgets.QGroupBox(CrossValidationDlg)
        self.groupBox_boundary.setEnabled(True)
        font = QtGui.QFont()
        font.setKerning(True)
        self.groupBox_boundary.setFont(font)
        self.groupBox_boundary.setFlat(False)
        self.groupBox_boundary.setCheckable(True)
        self.groupBox_boundary.setChecked(True)
        self.groupBox_boundary.setObjectName(_fromUtf8("groupBox_boundary"))
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_boundary)
        self.gridLayout.setMargin(1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtWidgets.QLabel(self.groupBox_boundary)
        self.label_5.setEnabled(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_boundary)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_ymax = QtWidgets.QLineEdit(self.groupBox_boundary)
        self.lineEdit_ymax.setEnabled(True)
        self.lineEdit_ymax.setObjectName(_fromUtf8("lineEdit_ymax"))
        self.gridLayout.addWidget(self.lineEdit_ymax, 1, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_boundary)
        self.label_3.setEnabled(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_boundary)
        self.label_7.setEnabled(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.lineEdit_xmin = QtWidgets.QLineEdit(self.groupBox_boundary)
        self.lineEdit_xmin.setEnabled(True)
        self.lineEdit_xmin.setText(_fromUtf8(""))
        self.lineEdit_xmin.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_xmin.setObjectName(_fromUtf8("lineEdit_xmin"))
        self.gridLayout.addWidget(self.lineEdit_xmin, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_boundary)
        self.label_6.setEnabled(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 3, 1, 1)
        self.lineEdit_ymin = QtWidgets.QLineEdit(self.groupBox_boundary)
        self.lineEdit_ymin.setEnabled(True)
        self.lineEdit_ymin.setObjectName(_fromUtf8("lineEdit_ymin"))
        self.gridLayout.addWidget(self.lineEdit_ymin, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_boundary)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_xmax = QtWidgets.QLineEdit(self.groupBox_boundary)
        self.lineEdit_xmax.setEnabled(True)
        self.lineEdit_xmax.setObjectName(_fromUtf8("lineEdit_xmax"))
        self.gridLayout.addWidget(self.lineEdit_xmax, 0, 4, 1, 1)
        self.lineEdit_tmax = QtWidgets.QLineEdit(self.groupBox_boundary)
        self.lineEdit_tmax.setEnabled(True)
        self.lineEdit_tmax.setObjectName(_fromUtf8("lineEdit_tmax"))
        self.gridLayout.addWidget(self.lineEdit_tmax, 2, 4, 1, 1)
        self.lineEdit_tmin = QtWidgets.QLineEdit(self.groupBox_boundary)
        self.lineEdit_tmin.setEnabled(True)
        self.lineEdit_tmin.setObjectName(_fromUtf8("lineEdit_tmin"))
        self.gridLayout.addWidget(self.lineEdit_tmin, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_boundary)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_spatial_result = QtWidgets.QPushButton(CrossValidationDlg)
        self.pushButton_spatial_result.setEnabled(False)
        self.pushButton_spatial_result.setObjectName(_fromUtf8("pushButton_spatial_result"))
        self.horizontalLayout_3.addWidget(self.pushButton_spatial_result)
        self.pushButton_temporal_result = QtWidgets.QPushButton(CrossValidationDlg)
        self.pushButton_temporal_result.setEnabled(False)
        self.pushButton_temporal_result.setObjectName(_fromUtf8("pushButton_temporal_result"))
        self.horizontalLayout_3.addWidget(self.pushButton_temporal_result)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_run = QtWidgets.QPushButton(CrossValidationDlg)
        self.pushButton_run.setObjectName(_fromUtf8("pushButton_run"))
        self.horizontalLayout_3.addWidget(self.pushButton_run)
        self.pushButton_cancel = QtWidgets.QPushButton(CrossValidationDlg)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.horizontalLayout_3.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(CrossValidationDlg)
        QtCore.QMetaObject.connectSlotsByName(CrossValidationDlg)

    def retranslateUi(self, CrossValidationDlg):
        CrossValidationDlg.setWindowTitle(_translate("CrossValidationDlg", "Cross Validation Dialog", None))
        self.label_9.setText(_translate("CrossValidationDlg", "Sample Type:", None))
        self.radioButton_hard.setText(_translate("CrossValidationDlg", "Hard Data Only", None))
        self.radioButton_soft.setText(_translate("CrossValidationDlg", "Soft Data Only", None))
        self.radioButton_both.setText(_translate("CrossValidationDlg", "Hard and Soft Data", None))
        self.label.setText(_translate("CrossValidationDlg", "Sample Size:", None))
        self.label_n.setText(_translate("CrossValidationDlg", "Label", None))
        self.groupBox_boundary.setTitle(_translate("CrossValidationDlg", "Sample Boundary Clipped", None))
        self.label_5.setText(_translate("CrossValidationDlg", "Tmax", None))
        self.label_4.setText(_translate("CrossValidationDlg", "Tmin", None))
        self.label_3.setText(_translate("CrossValidationDlg", "Ymin", None))
        self.label_7.setText(_translate("CrossValidationDlg", "Xmax", None))
        self.label_6.setText(_translate("CrossValidationDlg", "Ymax", None))
        self.label_2.setText(_translate("CrossValidationDlg", "Xmin", None))
        self.pushButton_spatial_result.setText(_translate("CrossValidationDlg", "View Spatial Result", None))
        self.pushButton_temporal_result.setText(_translate("CrossValidationDlg", "View Temporal Result", None))
        self.label_workers.setText(_translate("CrossValidationDlg", "Parallel Workers:", None))
        self.pushButton_run.setText(_translate("CrossValidationDlg", "Run", None))
        self.pushButton_cancel.setText(_translate("CrossValidationDlg", "Close", None))

