# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\scku\Desktop\GitRepos\STARBME\starbme_src\gui\ui\ui_MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets

def _fromUtf8(s):
    return s

def _translate(context, text, disambig):
    return QtCore.QCoreApplication.translate(context, text)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(514, 267)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet(_fromUtf8("QWidget#centralwidget { background: white}"))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setStyleSheet(_fromUtf8("QFrame {background: white}"))
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.verticalFrame.setObjectName(_fromUtf8("verticalFrame"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_10.addWidget(self.label)
        self.pushButton_crs = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_crs.sizePolicy().hasHeightForWidth())
        self.pushButton_crs.setSizePolicy(sizePolicy)
        self.pushButton_crs.setObjectName(_fromUtf8("pushButton_crs"))
        self.horizontalLayout_10.addWidget(self.pushButton_crs)
        self.checkBox_crs = QtWidgets.QCheckBox(self.verticalFrame)
        self.checkBox_crs.setObjectName(_fromUtf8("checkBox_crs"))
        self.horizontalLayout_10.addWidget(self.checkBox_crs)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtWidgets.QLabel(self.verticalFrame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.pushButton_setdata = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_setdata.sizePolicy().hasHeightForWidth())
        self.pushButton_setdata.setSizePolicy(sizePolicy)
        self.pushButton_setdata.setObjectName(_fromUtf8("pushButton_setdata"))
        self.horizontalLayout.addWidget(self.pushButton_setdata)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_addbackgroundshapefile = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_addbackgroundshapefile.sizePolicy().hasHeightForWidth())
        self.pushButton_addbackgroundshapefile.setSizePolicy(sizePolicy)
        self.pushButton_addbackgroundshapefile.setObjectName(_fromUtf8("pushButton_addbackgroundshapefile"))
        self.horizontalLayout.addWidget(self.pushButton_addbackgroundshapefile)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtWidgets.QLabel(self.verticalFrame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_detrendmethod = QtWidgets.QComboBox(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_detrendmethod.sizePolicy().hasHeightForWidth())
        self.comboBox_detrendmethod.setSizePolicy(sizePolicy)
        self.comboBox_detrendmethod.setObjectName(_fromUtf8("comboBox_detrendmethod"))
        self.comboBox_detrendmethod.addItem(_fromUtf8(""))
        self.comboBox_detrendmethod.addItem(_fromUtf8(""))
        self.comboBox_detrendmethod.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox_detrendmethod)
        self.pushButton_detrend = QtWidgets.QPushButton(self.verticalFrame)
        self.pushButton_detrend.setEnabled(False)
        self.pushButton_detrend.setObjectName(_fromUtf8("pushButton_detrend"))
        self.horizontalLayout_2.addWidget(self.pushButton_detrend)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtWidgets.QLabel(self.verticalFrame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.pushButton_plotandfit = QtWidgets.QPushButton(self.verticalFrame)
        self.pushButton_plotandfit.setEnabled(False)
        self.pushButton_plotandfit.setObjectName(_fromUtf8("pushButton_plotandfit"))
        self.horizontalLayout_4.addWidget(self.pushButton_plotandfit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_10 = QtWidgets.QLabel(self.verticalFrame)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_8.addWidget(self.label_10)
        self.pushButton_setestimateddata = QtWidgets.QPushButton(self.verticalFrame)
        self.pushButton_setestimateddata.setObjectName(_fromUtf8("pushButton_setestimateddata"))
        self.horizontalLayout_8.addWidget(self.pushButton_setestimateddata)
        self.pushButton_estimate = QtWidgets.QPushButton(self.verticalFrame)
        self.pushButton_estimate.setEnabled(False)
        self.pushButton_estimate.setObjectName(_fromUtf8("pushButton_estimate"))
        self.horizontalLayout_8.addWidget(self.pushButton_estimate)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.pushButton_crossvalidation = QtWidgets.QPushButton(self.verticalFrame)
        self.pushButton_crossvalidation.setObjectName(_fromUtf8("pushButton_crossvalidation"))
        self.horizontalLayout_8.addWidget(self.pushButton_crossvalidation)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_11 = QtWidgets.QLabel(self.verticalFrame)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_5.addWidget(self.label_11)
        self.comboBox_app = QtWidgets.QComboBox(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_app.sizePolicy().hasHeightForWidth())
        self.comboBox_app.setSizePolicy(sizePolicy)
        self.comboBox_app.setObjectName(_fromUtf8("comboBox_app"))
        self.comboBox_app.addItem(_fromUtf8(""))
        self.comboBox_app.addItem(_fromUtf8(""))
        self.comboBox_app.addItem(_fromUtf8(""))
        self.comboBox_app.addItem(_fromUtf8(""))
        self.comboBox_app.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_app)
        self.pushButton_doapp = QtWidgets.QPushButton(self.verticalFrame)
        self.pushButton_doapp.setEnabled(False)
        self.pushButton_doapp.setObjectName(_fromUtf8("pushButton_doapp"))
        self.horizontalLayout_5.addWidget(self.pushButton_doapp)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addWidget(self.verticalFrame, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 514, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        self.menu_about = QtWidgets.QMenu(self.menubar)
        self.menu_about.setObjectName(_fromUtf8("menu_about"))
        self.menu_config = QtWidgets.QMenu(self.menubar)
        self.menu_config.setObjectName(_fromUtf8("menu_config"))
        self.menu_view = QtWidgets.QMenu(self.menubar)
        self.menu_view.setObjectName(_fromUtf8("menu_view"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.action_new = QtWidgets.QAction(MainWindow)
        self.action_new.setObjectName(_fromUtf8("action_new"))
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName(_fromUtf8("action_save"))
        self.action_saveas = QtWidgets.QAction(MainWindow)
        self.action_saveas.setObjectName(_fromUtf8("action_saveas"))
        self.action_option = QtWidgets.QAction(MainWindow)
        self.action_option.setObjectName(_fromUtf8("action_option"))
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_new)
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_saveas)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_quit)
        self.menu_about.addAction(self.action_about)
        self.menu_config.addAction(self.action_option)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_config.menuAction())
        self.menubar.addAction(self.menu_about.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "bmeobj.bme - Space-Time Analysis Rendering with Bayesian Maximum Entropy ( Version x.y.z )", None))
        self.label.setText(_translate("MainWindow", "0. Set Your Data CRS", None))
        self.pushButton_crs.setText(_translate("MainWindow", "Choose...", None))
        self.checkBox_crs.setText(_translate("MainWindow", "I will set it later", None))
        self.label_5.setText(_translate("MainWindow", "1. Specify Data for STAR-BME", None))
        self.pushButton_setdata.setText(_translate("MainWindow", "Select", None))
        self.pushButton_addbackgroundshapefile.setText(_translate("MainWindow", "Add Background Shapefile...", None))
        self.label_2.setText(_translate("MainWindow", "2. Decompose Data to Trend and Residual By...", None))
        self.comboBox_detrendmethod.setItemText(0, _translate("MainWindow", "No Detrending", None))
        self.comboBox_detrendmethod.setItemText(1, _translate("MainWindow", "Kernel Smoothing", None))
        self.comboBox_detrendmethod.setItemText(2, _translate("MainWindow", "STMean", None))
        self.pushButton_detrend.setText(_translate("MainWindow", "Run...", None))
        self.label_7.setText(_translate("MainWindow", "3. Estimate, Fit, and Plot Covariance", None))
        self.pushButton_plotandfit.setText(_translate("MainWindow", "Model Covariance", None))
        self.label_10.setText(_translate("MainWindow", "4. Prediction", None))
        self.pushButton_setestimateddata.setText(_translate("MainWindow", "Specify Locations", None))
        self.pushButton_estimate.setText(_translate("MainWindow", "Predict", None))
        self.pushButton_crossvalidation.setText(_translate("MainWindow", "Cross Validation", None))
        self.label_11.setText(_translate("MainWindow", "5. Specify Task for Results", None))
        self.comboBox_app.setItemText(0, _translate("MainWindow", "Add Result to QGIS (Vector)", None))
        self.comboBox_app.setItemText(1, _translate("MainWindow", "Add Result to QGIS (Raster)", None))
        self.comboBox_app.setItemText(2, _translate("MainWindow", "Add Result to QGIS (Raster with Mask)", None))
        self.comboBox_app.setItemText(3, _translate("MainWindow", "Export Result to File", None))
        self.comboBox_app.setItemText(4, _translate("MainWindow", "Export Result to PNG", None))
        self.pushButton_doapp.setText(_translate("MainWindow", "Go...", None))
        self.menu_file.setTitle(_translate("MainWindow", "File", None))
        self.menu_about.setTitle(_translate("MainWindow", "About", None))
        self.menu_config.setTitle(_translate("MainWindow", "Configure", None))
        self.menu_view.setTitle(_translate("MainWindow", "View", None))
        self.action_open.setText(_translate("MainWindow", "Open...", None))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.action_new.setText(_translate("MainWindow", "New", None))
        self.action_new.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.action_quit.setText(_translate("MainWindow", "Quit", None))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_about.setText(_translate("MainWindow", "STAR-BME", None))
        self.action_save.setText(_translate("MainWindow", "Save", None))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_saveas.setText(_translate("MainWindow", "Save as...", None))
        self.action_saveas.setShortcut(_translate("MainWindow", "Ctrl+A", None))
        self.action_option.setText(_translate("MainWindow", "Option...", None))

