# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\scku\Desktop\GitRepos\STARBME\starbme_src\gui\ui\ui_PlotAndFitCovDlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets

def _fromUtf8(s):
    return s

def _translate(context, text, disambig):
    return QtCore.QCoreApplication.translate(context, text)

class Ui_PlotAndFitCovDlg(object):
    def setupUi(self, PlotAndFitCovDlg):
        PlotAndFitCovDlg.setObjectName(_fromUtf8("PlotAndFitCovDlg"))
        PlotAndFitCovDlg.setWindowModality(QtCore.Qt.WindowModal)
        PlotAndFitCovDlg.resize(952, 476)
        PlotAndFitCovDlg.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(PlotAndFitCovDlg)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.widget = QtWidgets.QWidget(PlotAndFitCovDlg)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(480, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_50 = QtWidgets.QLabel(self.widget)
        self.label_50.setMinimumSize(QtCore.QSize(110, 16))
        self.label_50.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_4.addWidget(self.label_50)
        self.lineEdit_sl = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_sl.sizePolicy().hasHeightForWidth())
        self.lineEdit_sl.setSizePolicy(sizePolicy)
        self.lineEdit_sl.setObjectName(_fromUtf8("lineEdit_sl"))
        self.horizontalLayout_4.addWidget(self.lineEdit_sl)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_51 = QtWidgets.QLabel(self.widget)
        self.label_51.setMinimumSize(QtCore.QSize(111, 16))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.horizontalLayout_5.addWidget(self.label_51)
        self.lineEdit_sn = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_sn.setObjectName(_fromUtf8("lineEdit_sn"))
        self.horizontalLayout_5.addWidget(self.lineEdit_sn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_52 = QtWidgets.QLabel(self.widget)
        self.label_52.setMinimumSize(QtCore.QSize(131, 16))
        self.label_52.setMaximumSize(QtCore.QSize(131, 16))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.horizontalLayout_7.addWidget(self.label_52)
        self.lineEdit_sr = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_sr.setObjectName(_fromUtf8("lineEdit_sr"))
        self.horizontalLayout_7.addWidget(self.lineEdit_sr)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_12.addLayout(self.verticalLayout_4)
        self.temporalcalcovwgt = QtWidgets.QWidget(self.widget)
        self.temporalcalcovwgt.setObjectName(_fromUtf8("temporalcalcovwgt"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.temporalcalcovwgt)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_53 = QtWidgets.QLabel(self.temporalcalcovwgt)
        self.label_53.setMinimumSize(QtCore.QSize(120, 20))
        self.label_53.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.horizontalLayout.addWidget(self.label_53)
        self.lineEdit_tl = QtWidgets.QLineEdit(self.temporalcalcovwgt)
        self.lineEdit_tl.setObjectName(_fromUtf8("lineEdit_tl"))
        self.horizontalLayout.addWidget(self.lineEdit_tl)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_54 = QtWidgets.QLabel(self.temporalcalcovwgt)
        self.label_54.setMinimumSize(QtCore.QSize(131, 16))
        self.label_54.setMaximumSize(QtCore.QSize(131, 16))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.horizontalLayout_2.addWidget(self.label_54)
        self.lineEdit_tn = QtWidgets.QLineEdit(self.temporalcalcovwgt)
        self.lineEdit_tn.setObjectName(_fromUtf8("lineEdit_tn"))
        self.horizontalLayout_2.addWidget(self.lineEdit_tn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_55 = QtWidgets.QLabel(self.temporalcalcovwgt)
        self.label_55.setMinimumSize(QtCore.QSize(151, 16))
        self.label_55.setMaximumSize(QtCore.QSize(151, 16))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.horizontalLayout_3.addWidget(self.label_55)
        self.lineEdit_tr = QtWidgets.QLineEdit(self.temporalcalcovwgt)
        self.lineEdit_tr.setObjectName(_fromUtf8("lineEdit_tr"))
        self.horizontalLayout_3.addWidget(self.lineEdit_tr)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_12.addWidget(self.temporalcalcovwgt)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.pushButton_plot = QtWidgets.QPushButton(self.widget)
        self.pushButton_plot.setObjectName(_fromUtf8("pushButton_plot"))
        self.horizontalLayout_15.addWidget(self.pushButton_plot)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_10.addLayout(self.verticalLayout_6)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_10.addWidget(self.line)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_11.addWidget(self.label_5)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_13.addWidget(self.label_15)
        self.comboBox_nestnumber = QtWidgets.QComboBox(self.widget)
        self.comboBox_nestnumber.setObjectName(_fromUtf8("comboBox_nestnumber"))
        self.comboBox_nestnumber.addItem(_fromUtf8(""))
        self.comboBox_nestnumber.addItem(_fromUtf8(""))
        self.comboBox_nestnumber.addItem(_fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.comboBox_nestnumber)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_13.addWidget(self.label_23)
        self.label_1 = QtWidgets.QLabel(self.widget)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.horizontalLayout_13.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_13.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_13.addWidget(self.label_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_9.addWidget(self.label)
        self.comboBox_method = QtWidgets.QComboBox(self.widget)
        self.comboBox_method.setObjectName(_fromUtf8("comboBox_method"))
        self.comboBox_method.addItem(_fromUtf8(""))
        self.comboBox_method.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.comboBox_method)
        self.pushButton_show = QtWidgets.QPushButton(self.widget)
        self.pushButton_show.setEnabled(False)
        self.pushButton_show.setObjectName(_fromUtf8("pushButton_show"))
        self.horizontalLayout_9.addWidget(self.pushButton_show)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_9.setMargin(1)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.lineEdit_c1 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_c1.setMinimumSize(QtCore.QSize(69, 20))
        self.lineEdit_c1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_c1.setObjectName(_fromUtf8("lineEdit_c1"))
        self.horizontalLayout_11.addWidget(self.lineEdit_c1)
        self.label_12 = QtWidgets.QLabel(self.widget_7)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_11.addWidget(self.label_12)
        self.comboBox_s1 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_s1.setMinimumSize(QtCore.QSize(83, 20))
        self.comboBox_s1.setObjectName(_fromUtf8("comboBox_s1"))
        self.comboBox_s1.addItem(_fromUtf8(""))
        self.comboBox_s1.addItem(_fromUtf8(""))
        self.comboBox_s1.addItem(_fromUtf8(""))
        self.comboBox_s1.addItem(_fromUtf8(""))
        self.comboBox_s1.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.comboBox_s1)
        self.label_26 = QtWidgets.QLabel(self.widget_7)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_11.addWidget(self.label_26)
        self.lineEdit_s1 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_s1.setMinimumSize(QtCore.QSize(68, 20))
        self.lineEdit_s1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_s1.setObjectName(_fromUtf8("lineEdit_s1"))
        self.horizontalLayout_11.addWidget(self.lineEdit_s1)
        self.label_t1 = QtWidgets.QLabel(self.widget_7)
        self.label_t1.setObjectName(_fromUtf8("label_t1"))
        self.horizontalLayout_11.addWidget(self.label_t1)
        self.temporalfitcovwgt_1 = QtWidgets.QWidget(self.widget_7)
        self.temporalfitcovwgt_1.setObjectName(_fromUtf8("temporalfitcovwgt_1"))
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.temporalfitcovwgt_1)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_6 = QtWidgets.QLabel(self.temporalfitcovwgt_1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_16.addWidget(self.label_6)
        self.comboBox_t1 = QtWidgets.QComboBox(self.temporalfitcovwgt_1)
        self.comboBox_t1.setObjectName(_fromUtf8("comboBox_t1"))
        self.comboBox_t1.addItem(_fromUtf8(""))
        self.comboBox_t1.addItem(_fromUtf8(""))
        self.comboBox_t1.addItem(_fromUtf8(""))
        self.comboBox_t1.addItem(_fromUtf8(""))
        self.comboBox_t1.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.comboBox_t1)
        self.label_30 = QtWidgets.QLabel(self.temporalfitcovwgt_1)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_16.addWidget(self.label_30)
        self.lineEdit_t1 = QtWidgets.QLineEdit(self.temporalfitcovwgt_1)
        self.lineEdit_t1.setMinimumSize(QtCore.QSize(69, 20))
        self.lineEdit_t1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_t1.setObjectName(_fromUtf8("lineEdit_t1"))
        self.horizontalLayout_16.addWidget(self.lineEdit_t1)
        self.label_31 = QtWidgets.QLabel(self.temporalfitcovwgt_1)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_16.addWidget(self.label_31)
        self.horizontalLayout_11.addWidget(self.temporalfitcovwgt_1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.verticalLayout_11.addWidget(self.widget_7)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setEnabled(False)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_7.setMargin(1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_7.addWidget(self.label_14)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.lineEdit_c2 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_c2.setMinimumSize(QtCore.QSize(69, 20))
        self.lineEdit_c2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_c2.setObjectName(_fromUtf8("lineEdit_c2"))
        self.horizontalLayout_10.addWidget(self.lineEdit_c2)
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.comboBox_s2 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_s2.setMinimumSize(QtCore.QSize(83, 20))
        self.comboBox_s2.setObjectName(_fromUtf8("comboBox_s2"))
        self.comboBox_s2.addItem(_fromUtf8(""))
        self.comboBox_s2.addItem(_fromUtf8(""))
        self.comboBox_s2.addItem(_fromUtf8(""))
        self.comboBox_s2.addItem(_fromUtf8(""))
        self.comboBox_s2.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.comboBox_s2)
        self.label_11 = QtWidgets.QLabel(self.widget_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        self.lineEdit_s2 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_s2.setMinimumSize(QtCore.QSize(68, 20))
        self.lineEdit_s2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_s2.setObjectName(_fromUtf8("lineEdit_s2"))
        self.horizontalLayout_10.addWidget(self.lineEdit_s2)
        self.label_t1_2 = QtWidgets.QLabel(self.widget_4)
        self.label_t1_2.setObjectName(_fromUtf8("label_t1_2"))
        self.horizontalLayout_10.addWidget(self.label_t1_2)
        self.temporalfitcovwgt_2 = QtWidgets.QWidget(self.widget_4)
        self.temporalfitcovwgt_2.setObjectName(_fromUtf8("temporalfitcovwgt_2"))
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.temporalfitcovwgt_2)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_7 = QtWidgets.QLabel(self.temporalfitcovwgt_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_17.addWidget(self.label_7)
        self.comboBox_t2 = QtWidgets.QComboBox(self.temporalfitcovwgt_2)
        self.comboBox_t2.setObjectName(_fromUtf8("comboBox_t2"))
        self.comboBox_t2.addItem(_fromUtf8(""))
        self.comboBox_t2.addItem(_fromUtf8(""))
        self.comboBox_t2.addItem(_fromUtf8(""))
        self.comboBox_t2.addItem(_fromUtf8(""))
        self.comboBox_t2.addItem(_fromUtf8(""))
        self.horizontalLayout_17.addWidget(self.comboBox_t2)
        self.label_18 = QtWidgets.QLabel(self.temporalfitcovwgt_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_17.addWidget(self.label_18)
        self.lineEdit_t2 = QtWidgets.QLineEdit(self.temporalfitcovwgt_2)
        self.lineEdit_t2.setMinimumSize(QtCore.QSize(69, 20))
        self.lineEdit_t2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_t2.setObjectName(_fromUtf8("lineEdit_t2"))
        self.horizontalLayout_17.addWidget(self.lineEdit_t2)
        self.label_21 = QtWidgets.QLabel(self.temporalfitcovwgt_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_17.addWidget(self.label_21)
        self.horizontalLayout_10.addWidget(self.temporalfitcovwgt_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_11.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setEnabled(False)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_8.setMargin(1)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_19 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_8.addWidget(self.label_19)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lineEdit_c3 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_c3.setMinimumSize(QtCore.QSize(69, 20))
        self.lineEdit_c3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_c3.setObjectName(_fromUtf8("lineEdit_c3"))
        self.horizontalLayout_8.addWidget(self.lineEdit_c3)
        self.label_9 = QtWidgets.QLabel(self.widget_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.comboBox_s3 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_s3.setMinimumSize(QtCore.QSize(83, 20))
        self.comboBox_s3.setObjectName(_fromUtf8("comboBox_s3"))
        self.comboBox_s3.addItem(_fromUtf8(""))
        self.comboBox_s3.addItem(_fromUtf8(""))
        self.comboBox_s3.addItem(_fromUtf8(""))
        self.comboBox_s3.addItem(_fromUtf8(""))
        self.comboBox_s3.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.comboBox_s3)
        self.label_13 = QtWidgets.QLabel(self.widget_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_8.addWidget(self.label_13)
        self.lineEdit_s3 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_s3.setMinimumSize(QtCore.QSize(68, 20))
        self.lineEdit_s3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_s3.setObjectName(_fromUtf8("lineEdit_s3"))
        self.horizontalLayout_8.addWidget(self.lineEdit_s3)
        self.label_t1_3 = QtWidgets.QLabel(self.widget_5)
        self.label_t1_3.setObjectName(_fromUtf8("label_t1_3"))
        self.horizontalLayout_8.addWidget(self.label_t1_3)
        self.temporalfitcovwgt_3 = QtWidgets.QWidget(self.widget_5)
        self.temporalfitcovwgt_3.setObjectName(_fromUtf8("temporalfitcovwgt_3"))
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.temporalfitcovwgt_3)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_8 = QtWidgets.QLabel(self.temporalfitcovwgt_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_18.addWidget(self.label_8)
        self.comboBox_t3 = QtWidgets.QComboBox(self.temporalfitcovwgt_3)
        self.comboBox_t3.setObjectName(_fromUtf8("comboBox_t3"))
        self.comboBox_t3.addItem(_fromUtf8(""))
        self.comboBox_t3.addItem(_fromUtf8(""))
        self.comboBox_t3.addItem(_fromUtf8(""))
        self.comboBox_t3.addItem(_fromUtf8(""))
        self.comboBox_t3.addItem(_fromUtf8(""))
        self.horizontalLayout_18.addWidget(self.comboBox_t3)
        self.label_28 = QtWidgets.QLabel(self.temporalfitcovwgt_3)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_18.addWidget(self.label_28)
        self.lineEdit_t3 = QtWidgets.QLineEdit(self.temporalfitcovwgt_3)
        self.lineEdit_t3.setMinimumSize(QtCore.QSize(69, 20))
        self.lineEdit_t3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_t3.setObjectName(_fromUtf8("lineEdit_t3"))
        self.horizontalLayout_18.addWidget(self.lineEdit_t3)
        self.label_29 = QtWidgets.QLabel(self.temporalfitcovwgt_3)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_18.addWidget(self.label_29)
        self.horizontalLayout_8.addWidget(self.temporalfitcovwgt_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.verticalLayout_11.addWidget(self.widget_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_fit = QtWidgets.QPushButton(self.widget)
        self.pushButton_fit.setEnabled(False)
        self.pushButton_fit.setObjectName(_fromUtf8("pushButton_fit"))
        self.horizontalLayout_6.addWidget(self.pushButton_fit)
        self.checkBox_autofit = QtWidgets.QCheckBox(self.widget)
        self.checkBox_autofit.setEnabled(False)
        self.checkBox_autofit.setObjectName(_fromUtf8("checkBox_autofit"))
        self.horizontalLayout_6.addWidget(self.checkBox_autofit)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_11.addWidget(self.line_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem9)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.pushButton_ok = QtWidgets.QPushButton(self.widget)
        self.pushButton_ok.setEnabled(False)
        self.pushButton_ok.setObjectName(_fromUtf8("pushButton_ok"))
        self.horizontalLayout_14.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.horizontalLayout_14.addWidget(self.pushButton_cancel)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.horizontalLayout_19.addWidget(self.widget)
        self.tabWidget = QtWidgets.QTabWidget(PlotAndFitCovDlg)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mplWidget_2d = MplWidget(self.tab)
        self.mplWidget_2d.setObjectName(_fromUtf8("mplWidget_2d"))
        self.verticalLayout.addWidget(self.mplWidget_2d)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mplWidget_3d = MplWidget(self.tab_2)
        self.mplWidget_3d.setObjectName(_fromUtf8("mplWidget_3d"))
        self.verticalLayout_2.addWidget(self.mplWidget_3d)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_19.addWidget(self.tabWidget)

        self.retranslateUi(PlotAndFitCovDlg)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PlotAndFitCovDlg)

    def retranslateUi(self, PlotAndFitCovDlg):
        PlotAndFitCovDlg.setWindowTitle(_translate("PlotAndFitCovDlg", "Covariance Analysis", None))
        self.label_4.setText(_translate("PlotAndFitCovDlg", "<html><head/><body><p><span style=\" font-family:\'Helvetica,sans-serif\'; font-weight:600; color:#000000;\">Estimate Empirical Covariance</span><span style=\" font-weight:600; color:#000000;\">:</span></p></body></html>", None))
        self.label_50.setText(_translate("PlotAndFitCovDlg", "Spatial Distance Limit:", None))
        self.lineEdit_sl.setText(_translate("PlotAndFitCovDlg", "20000", None))
        self.label_51.setText(_translate("PlotAndFitCovDlg", "Number of Spatial Lags:", None))
        self.lineEdit_sn.setText(_translate("PlotAndFitCovDlg", "8", None))
        self.label_52.setText(_translate("PlotAndFitCovDlg", "Spatial Lag Tolerance:", None))
        self.lineEdit_sr.setText(_translate("PlotAndFitCovDlg", "2500", None))
        self.label_53.setText(_translate("PlotAndFitCovDlg", "Temporal Distance Limit:", None))
        self.lineEdit_tl.setText(_translate("PlotAndFitCovDlg", "20", None))
        self.label_54.setText(_translate("PlotAndFitCovDlg", "Number of Temporal Lags:", None))
        self.lineEdit_tn.setText(_translate("PlotAndFitCovDlg", "21", None))
        self.label_55.setText(_translate("PlotAndFitCovDlg", "Temporal Lag Tolerance:", None))
        self.lineEdit_tr.setText(_translate("PlotAndFitCovDlg", "0.5", None))
        self.pushButton_plot.setText(_translate("PlotAndFitCovDlg", "Plot Empirical Covariance", None))
        self.label_5.setText(_translate("PlotAndFitCovDlg", "<html><head/><body><p><span style=\" font-family:\'Helvetica,sans-serif\'; font-weight:600; color:#000000;\">Fit Covariance Model:</span></p></body></html>", None))
        self.label_15.setText(_translate("PlotAndFitCovDlg", "Nest Number:", None))
        self.comboBox_nestnumber.setItemText(0, _translate("PlotAndFitCovDlg", "1", None))
        self.comboBox_nestnumber.setItemText(1, _translate("PlotAndFitCovDlg", "2", None))
        self.comboBox_nestnumber.setItemText(2, _translate("PlotAndFitCovDlg", "3", None))
        self.label_23.setText(_translate("PlotAndFitCovDlg", "Fitting Model:", None))
        self.label_1.setText(_translate("PlotAndFitCovDlg", "C1*K(S1)*K(T1)", None))
        self.label_2.setText(_translate("PlotAndFitCovDlg", "+C2*K(S2)*K(T2)", None))
        self.label_3.setText(_translate("PlotAndFitCovDlg", "+C3*K(S3)*K(T3)", None))
        self.label.setText(_translate("PlotAndFitCovDlg", "Specify parameters (below) or fit them automatically by", None))
        self.comboBox_method.setItemText(0, _translate("PlotAndFitCovDlg", "BOBYQA", None))
        self.comboBox_method.setItemText(1, _translate("PlotAndFitCovDlg", "PSO", None))
        self.pushButton_show.setText(_translate("PlotAndFitCovDlg", "Fit Auto", None))
        self.lineEdit_c1.setText(_translate("PlotAndFitCovDlg", "15", None))
        self.label_12.setText(_translate("PlotAndFitCovDlg", "*", None))
        self.comboBox_s1.setItemText(0, _translate("PlotAndFitCovDlg", "Gaussian", None))
        self.comboBox_s1.setItemText(1, _translate("PlotAndFitCovDlg", "Exponential", None))
        self.comboBox_s1.setItemText(2, _translate("PlotAndFitCovDlg", "Spherical", None))
        self.comboBox_s1.setItemText(3, _translate("PlotAndFitCovDlg", "Holecos", None))
        self.comboBox_s1.setItemText(4, _translate("PlotAndFitCovDlg", "Nugget", None))
        self.label_26.setText(_translate("PlotAndFitCovDlg", "(", None))
        self.lineEdit_s1.setText(_translate("PlotAndFitCovDlg", "2000", None))
        self.label_t1.setText(_translate("PlotAndFitCovDlg", ") ", None))
        self.label_6.setText(_translate("PlotAndFitCovDlg", "*", None))
        self.comboBox_t1.setItemText(0, _translate("PlotAndFitCovDlg", "Gaussian", None))
        self.comboBox_t1.setItemText(1, _translate("PlotAndFitCovDlg", "Exponential", None))
        self.comboBox_t1.setItemText(2, _translate("PlotAndFitCovDlg", "Spherical", None))
        self.comboBox_t1.setItemText(3, _translate("PlotAndFitCovDlg", "Holecos", None))
        self.comboBox_t1.setItemText(4, _translate("PlotAndFitCovDlg", "Nugget", None))
        self.label_30.setText(_translate("PlotAndFitCovDlg", "(", None))
        self.lineEdit_t1.setText(_translate("PlotAndFitCovDlg", "5", None))
        self.label_31.setText(_translate("PlotAndFitCovDlg", ")", None))
        self.label_14.setText(_translate("PlotAndFitCovDlg", "+", None))
        self.lineEdit_c2.setText(_translate("PlotAndFitCovDlg", "C2", None))
        self.label_10.setText(_translate("PlotAndFitCovDlg", "*", None))
        self.comboBox_s2.setItemText(0, _translate("PlotAndFitCovDlg", "Gaussian", None))
        self.comboBox_s2.setItemText(1, _translate("PlotAndFitCovDlg", "Exponential", None))
        self.comboBox_s2.setItemText(2, _translate("PlotAndFitCovDlg", "Spherical", None))
        self.comboBox_s2.setItemText(3, _translate("PlotAndFitCovDlg", "Holecos", None))
        self.comboBox_s2.setItemText(4, _translate("PlotAndFitCovDlg", "Nugget", None))
        self.label_11.setText(_translate("PlotAndFitCovDlg", "(", None))
        self.lineEdit_s2.setText(_translate("PlotAndFitCovDlg", "S2", None))
        self.label_t1_2.setText(_translate("PlotAndFitCovDlg", ") ", None))
        self.label_7.setText(_translate("PlotAndFitCovDlg", "*", None))
        self.comboBox_t2.setItemText(0, _translate("PlotAndFitCovDlg", "Gaussian", None))
        self.comboBox_t2.setItemText(1, _translate("PlotAndFitCovDlg", "Exponential", None))
        self.comboBox_t2.setItemText(2, _translate("PlotAndFitCovDlg", "Spherical", None))
        self.comboBox_t2.setItemText(3, _translate("PlotAndFitCovDlg", "Holecos", None))
        self.comboBox_t2.setItemText(4, _translate("PlotAndFitCovDlg", "Nugget", None))
        self.label_18.setText(_translate("PlotAndFitCovDlg", "(", None))
        self.lineEdit_t2.setText(_translate("PlotAndFitCovDlg", "T2", None))
        self.label_21.setText(_translate("PlotAndFitCovDlg", ")", None))
        self.label_19.setText(_translate("PlotAndFitCovDlg", "+", None))
        self.lineEdit_c3.setText(_translate("PlotAndFitCovDlg", "C3", None))
        self.label_9.setText(_translate("PlotAndFitCovDlg", "*", None))
        self.comboBox_s3.setItemText(0, _translate("PlotAndFitCovDlg", "Gaussian", None))
        self.comboBox_s3.setItemText(1, _translate("PlotAndFitCovDlg", "Exponential", None))
        self.comboBox_s3.setItemText(2, _translate("PlotAndFitCovDlg", "Spherical", None))
        self.comboBox_s3.setItemText(3, _translate("PlotAndFitCovDlg", "Holecos", None))
        self.comboBox_s3.setItemText(4, _translate("PlotAndFitCovDlg", "Nugget", None))
        self.label_13.setText(_translate("PlotAndFitCovDlg", "(", None))
        self.lineEdit_s3.setText(_translate("PlotAndFitCovDlg", "S3", None))
        self.label_t1_3.setText(_translate("PlotAndFitCovDlg", ") ", None))
        self.label_8.setText(_translate("PlotAndFitCovDlg", "*", None))
        self.comboBox_t3.setItemText(0, _translate("PlotAndFitCovDlg", "Gaussian", None))
        self.comboBox_t3.setItemText(1, _translate("PlotAndFitCovDlg", "Exponential", None))
        self.comboBox_t3.setItemText(2, _translate("PlotAndFitCovDlg", "Spherical", None))
        self.comboBox_t3.setItemText(3, _translate("PlotAndFitCovDlg", "Holecos", None))
        self.comboBox_t3.setItemText(4, _translate("PlotAndFitCovDlg", "Nugget", None))
        self.label_28.setText(_translate("PlotAndFitCovDlg", "(", None))
        self.lineEdit_t3.setText(_translate("PlotAndFitCovDlg", "T3", None))
        self.label_29.setText(_translate("PlotAndFitCovDlg", ")", None))
        self.pushButton_fit.setText(_translate("PlotAndFitCovDlg", "Fit Manually Selected Model", None))
        self.checkBox_autofit.setText(_translate("PlotAndFitCovDlg", "Fit Automatically When Parameters Changed", None))
        self.pushButton_ok.setText(_translate("PlotAndFitCovDlg", "Ok", None))
        self.pushButton_cancel.setText(_translate("PlotAndFitCovDlg", "Cancel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PlotAndFitCovDlg", "2D", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PlotAndFitCovDlg", "3D", None))

from .mplwidget import MplWidget
