# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\scku\Desktop\GitRepos\STARBME\starbme_src\gui\ui\ui_SelectParamByBobyqaDlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets

def _fromUtf8(s):
    return s

def _translate(context, text, disambig):
    return QtCore.QCoreApplication.translate(context, text)

class Ui_SelectParamByBobyqaDlg(object):
    def setupUi(self, SelectParamByBobyqaDlg):
        SelectParamByBobyqaDlg.setObjectName(_fromUtf8("SelectParamByBobyqaDlg"))
        SelectParamByBobyqaDlg.setWindowModality(QtCore.Qt.NonModal)
        SelectParamByBobyqaDlg.resize(458, 345)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(SelectParamByBobyqaDlg)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtWidgets.QTabWidget(SelectParamByBobyqaDlg)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.widget_1 = QtWidgets.QWidget(self.tab_2)
        self.widget_1.setObjectName(_fromUtf8("widget_1"))
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_1)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_c1_2 = QtWidgets.QLabel(self.widget_1)
        self.label_c1_2.setMinimumSize(QtCore.QSize(16, 0))
        self.label_c1_2.setObjectName(_fromUtf8("label_c1_2"))
        self.horizontalLayout_4.addWidget(self.label_c1_2)
        self.lineEdit_c1small = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_c1small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_c1small.setObjectName(_fromUtf8("lineEdit_c1small"))
        self.horizontalLayout_4.addWidget(self.lineEdit_c1small)
        self.label_16 = QtWidgets.QLabel(self.widget_1)
        self.label_16.setMinimumSize(QtCore.QSize(16, 0))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_4.addWidget(self.label_16)
        self.lineEdit_c1large = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_c1large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_c1large.setObjectName(_fromUtf8("lineEdit_c1large"))
        self.horizontalLayout_4.addWidget(self.lineEdit_c1large)
        self.lineEdit_c1guess = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_c1guess.setObjectName(_fromUtf8("lineEdit_c1guess"))
        self.horizontalLayout_4.addWidget(self.lineEdit_c1guess)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_c1_5 = QtWidgets.QLabel(self.widget_1)
        self.label_c1_5.setMinimumSize(QtCore.QSize(16, 0))
        self.label_c1_5.setObjectName(_fromUtf8("label_c1_5"))
        self.horizontalLayout_5.addWidget(self.label_c1_5)
        self.lineEdit_s1small = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_s1small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_s1small.setObjectName(_fromUtf8("lineEdit_s1small"))
        self.horizontalLayout_5.addWidget(self.lineEdit_s1small)
        self.label_18 = QtWidgets.QLabel(self.widget_1)
        self.label_18.setMinimumSize(QtCore.QSize(16, 0))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_5.addWidget(self.label_18)
        self.lineEdit_s1large = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_s1large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_s1large.setObjectName(_fromUtf8("lineEdit_s1large"))
        self.horizontalLayout_5.addWidget(self.lineEdit_s1large)
        self.lineEdit_s1guess = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_s1guess.setObjectName(_fromUtf8("lineEdit_s1guess"))
        self.horizontalLayout_5.addWidget(self.lineEdit_s1guess)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.twgt1 = QtWidgets.QWidget(self.widget_1)
        self.twgt1.setObjectName(_fromUtf8("twgt1"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.twgt1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_c1_8 = QtWidgets.QLabel(self.twgt1)
        self.label_c1_8.setMinimumSize(QtCore.QSize(16, 0))
        self.label_c1_8.setObjectName(_fromUtf8("label_c1_8"))
        self.horizontalLayout.addWidget(self.label_c1_8)
        self.lineEdit_t1small = QtWidgets.QLineEdit(self.twgt1)
        self.lineEdit_t1small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_t1small.setObjectName(_fromUtf8("lineEdit_t1small"))
        self.horizontalLayout.addWidget(self.lineEdit_t1small)
        self.label_17 = QtWidgets.QLabel(self.twgt1)
        self.label_17.setMinimumSize(QtCore.QSize(16, 0))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout.addWidget(self.label_17)
        self.lineEdit_t1large = QtWidgets.QLineEdit(self.twgt1)
        self.lineEdit_t1large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_t1large.setObjectName(_fromUtf8("lineEdit_t1large"))
        self.horizontalLayout.addWidget(self.lineEdit_t1large)
        self.lineEdit_t1guess = QtWidgets.QLineEdit(self.twgt1)
        self.lineEdit_t1guess.setObjectName(_fromUtf8("lineEdit_t1guess"))
        self.horizontalLayout.addWidget(self.lineEdit_t1guess)
        self.verticalLayout.addWidget(self.twgt1)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_5.addWidget(self.widget_1)
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setEnabled(True)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_c2range = QtWidgets.QLabel(self.widget_2)
        self.label_c2range.setEnabled(True)
        self.label_c2range.setMinimumSize(QtCore.QSize(16, 0))
        self.label_c2range.setObjectName(_fromUtf8("label_c2range"))
        self.horizontalLayout_7.addWidget(self.label_c2range)
        self.lineEdit_c2small = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_c2small.setEnabled(True)
        self.lineEdit_c2small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_c2small.setObjectName(_fromUtf8("lineEdit_c2small"))
        self.horizontalLayout_7.addWidget(self.lineEdit_c2small)
        self.label_c2dru = QtWidgets.QLabel(self.widget_2)
        self.label_c2dru.setEnabled(True)
        self.label_c2dru.setMinimumSize(QtCore.QSize(16, 0))
        self.label_c2dru.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c2dru.setObjectName(_fromUtf8("label_c2dru"))
        self.horizontalLayout_7.addWidget(self.label_c2dru)
        self.lineEdit_c2large = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_c2large.setEnabled(True)
        self.lineEdit_c2large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_c2large.setObjectName(_fromUtf8("lineEdit_c2large"))
        self.horizontalLayout_7.addWidget(self.lineEdit_c2large)
        self.lineEdit_c2guess = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_c2guess.setObjectName(_fromUtf8("lineEdit_c2guess"))
        self.horizontalLayout_7.addWidget(self.lineEdit_c2guess)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_s2range = QtWidgets.QLabel(self.widget_2)
        self.label_s2range.setEnabled(True)
        self.label_s2range.setMinimumSize(QtCore.QSize(16, 0))
        self.label_s2range.setObjectName(_fromUtf8("label_s2range"))
        self.horizontalLayout_11.addWidget(self.label_s2range)
        self.lineEdit_s2small = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_s2small.setEnabled(True)
        self.lineEdit_s2small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_s2small.setObjectName(_fromUtf8("lineEdit_s2small"))
        self.horizontalLayout_11.addWidget(self.lineEdit_s2small)
        self.label_s2dru = QtWidgets.QLabel(self.widget_2)
        self.label_s2dru.setEnabled(True)
        self.label_s2dru.setMinimumSize(QtCore.QSize(16, 0))
        self.label_s2dru.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s2dru.setObjectName(_fromUtf8("label_s2dru"))
        self.horizontalLayout_11.addWidget(self.label_s2dru)
        self.lineEdit_s2large = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_s2large.setEnabled(True)
        self.lineEdit_s2large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_s2large.setObjectName(_fromUtf8("lineEdit_s2large"))
        self.horizontalLayout_11.addWidget(self.lineEdit_s2large)
        self.lineEdit_s2guess = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_s2guess.setObjectName(_fromUtf8("lineEdit_s2guess"))
        self.horizontalLayout_11.addWidget(self.lineEdit_s2guess)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.twgt2 = QtWidgets.QWidget(self.widget_2)
        self.twgt2.setObjectName(_fromUtf8("twgt2"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.twgt2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_t2range = QtWidgets.QLabel(self.twgt2)
        self.label_t2range.setEnabled(True)
        self.label_t2range.setMinimumSize(QtCore.QSize(16, 0))
        self.label_t2range.setObjectName(_fromUtf8("label_t2range"))
        self.horizontalLayout_2.addWidget(self.label_t2range)
        self.lineEdit_t2small = QtWidgets.QLineEdit(self.twgt2)
        self.lineEdit_t2small.setEnabled(True)
        self.lineEdit_t2small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_t2small.setObjectName(_fromUtf8("lineEdit_t2small"))
        self.horizontalLayout_2.addWidget(self.lineEdit_t2small)
        self.label_t2dru = QtWidgets.QLabel(self.twgt2)
        self.label_t2dru.setEnabled(True)
        self.label_t2dru.setMinimumSize(QtCore.QSize(16, 0))
        self.label_t2dru.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t2dru.setObjectName(_fromUtf8("label_t2dru"))
        self.horizontalLayout_2.addWidget(self.label_t2dru)
        self.lineEdit_t2large = QtWidgets.QLineEdit(self.twgt2)
        self.lineEdit_t2large.setEnabled(True)
        self.lineEdit_t2large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_t2large.setObjectName(_fromUtf8("lineEdit_t2large"))
        self.horizontalLayout_2.addWidget(self.lineEdit_t2large)
        self.lineEdit_t2guess = QtWidgets.QLineEdit(self.twgt2)
        self.lineEdit_t2guess.setObjectName(_fromUtf8("lineEdit_t2guess"))
        self.horizontalLayout_2.addWidget(self.lineEdit_t2guess)
        self.verticalLayout_2.addWidget(self.twgt2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.tab_2)
        self.widget_3.setEnabled(True)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_c3range = QtWidgets.QLabel(self.widget_3)
        self.label_c3range.setEnabled(True)
        self.label_c3range.setMinimumSize(QtCore.QSize(16, 0))
        self.label_c3range.setObjectName(_fromUtf8("label_c3range"))
        self.horizontalLayout_12.addWidget(self.label_c3range)
        self.lineEdit_c3small = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_c3small.setEnabled(True)
        self.lineEdit_c3small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_c3small.setObjectName(_fromUtf8("lineEdit_c3small"))
        self.horizontalLayout_12.addWidget(self.lineEdit_c3small)
        self.label_c3dru = QtWidgets.QLabel(self.widget_3)
        self.label_c3dru.setEnabled(True)
        self.label_c3dru.setMinimumSize(QtCore.QSize(16, 0))
        self.label_c3dru.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c3dru.setObjectName(_fromUtf8("label_c3dru"))
        self.horizontalLayout_12.addWidget(self.label_c3dru)
        self.lineEdit_c3large = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_c3large.setEnabled(True)
        self.lineEdit_c3large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_c3large.setObjectName(_fromUtf8("lineEdit_c3large"))
        self.horizontalLayout_12.addWidget(self.lineEdit_c3large)
        self.lineEdit_c3guess = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_c3guess.setObjectName(_fromUtf8("lineEdit_c3guess"))
        self.horizontalLayout_12.addWidget(self.lineEdit_c3guess)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_s3range = QtWidgets.QLabel(self.widget_3)
        self.label_s3range.setEnabled(True)
        self.label_s3range.setMinimumSize(QtCore.QSize(16, 0))
        self.label_s3range.setObjectName(_fromUtf8("label_s3range"))
        self.horizontalLayout_13.addWidget(self.label_s3range)
        self.lineEdit_s3small = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_s3small.setEnabled(True)
        self.lineEdit_s3small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_s3small.setObjectName(_fromUtf8("lineEdit_s3small"))
        self.horizontalLayout_13.addWidget(self.lineEdit_s3small)
        self.label_s3dru = QtWidgets.QLabel(self.widget_3)
        self.label_s3dru.setEnabled(True)
        self.label_s3dru.setMinimumSize(QtCore.QSize(16, 0))
        self.label_s3dru.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s3dru.setObjectName(_fromUtf8("label_s3dru"))
        self.horizontalLayout_13.addWidget(self.label_s3dru)
        self.lineEdit_s3large = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_s3large.setEnabled(True)
        self.lineEdit_s3large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_s3large.setObjectName(_fromUtf8("lineEdit_s3large"))
        self.horizontalLayout_13.addWidget(self.lineEdit_s3large)
        self.lineEdit_s3guess = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_s3guess.setObjectName(_fromUtf8("lineEdit_s3guess"))
        self.horizontalLayout_13.addWidget(self.lineEdit_s3guess)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.twgt3 = QtWidgets.QWidget(self.widget_3)
        self.twgt3.setObjectName(_fromUtf8("twgt3"))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.twgt3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_t3range = QtWidgets.QLabel(self.twgt3)
        self.label_t3range.setEnabled(True)
        self.label_t3range.setMinimumSize(QtCore.QSize(16, 0))
        self.label_t3range.setObjectName(_fromUtf8("label_t3range"))
        self.horizontalLayout_3.addWidget(self.label_t3range)
        self.lineEdit_t3small = QtWidgets.QLineEdit(self.twgt3)
        self.lineEdit_t3small.setEnabled(True)
        self.lineEdit_t3small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_t3small.setObjectName(_fromUtf8("lineEdit_t3small"))
        self.horizontalLayout_3.addWidget(self.lineEdit_t3small)
        self.label_t3dru = QtWidgets.QLabel(self.twgt3)
        self.label_t3dru.setEnabled(True)
        self.label_t3dru.setMinimumSize(QtCore.QSize(16, 0))
        self.label_t3dru.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t3dru.setObjectName(_fromUtf8("label_t3dru"))
        self.horizontalLayout_3.addWidget(self.label_t3dru)
        self.lineEdit_t3large = QtWidgets.QLineEdit(self.twgt3)
        self.lineEdit_t3large.setEnabled(True)
        self.lineEdit_t3large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_t3large.setObjectName(_fromUtf8("lineEdit_t3large"))
        self.horizontalLayout_3.addWidget(self.lineEdit_t3large)
        self.lineEdit_t3guess = QtWidgets.QLineEdit(self.twgt3)
        self.lineEdit_t3guess.setObjectName(_fromUtf8("lineEdit_t3guess"))
        self.horizontalLayout_3.addWidget(self.lineEdit_t3guess)
        self.verticalLayout_4.addWidget(self.twgt3)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addWidget(self.widget_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_lastfitting = QtWidgets.QPushButton(SelectParamByBobyqaDlg)
        self.pushButton_lastfitting.setObjectName(_fromUtf8("pushButton_lastfitting"))
        self.horizontalLayout_6.addWidget(self.pushButton_lastfitting)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pushButton_calculate = QtWidgets.QPushButton(SelectParamByBobyqaDlg)
        self.pushButton_calculate.setObjectName(_fromUtf8("pushButton_calculate"))
        self.horizontalLayout_6.addWidget(self.pushButton_calculate)
        self.pushButton_close = QtWidgets.QPushButton(SelectParamByBobyqaDlg)
        self.pushButton_close.setObjectName(_fromUtf8("pushButton_close"))
        self.horizontalLayout_6.addWidget(self.pushButton_close)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)

        self.retranslateUi(SelectParamByBobyqaDlg)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SelectParamByBobyqaDlg)

    def retranslateUi(self, SelectParamByBobyqaDlg):
        SelectParamByBobyqaDlg.setWindowTitle(_translate("SelectParamByBobyqaDlg", "Select Parameters By Bound Optimization BY Quadratic Approximation", None))
        self.label_c1_2.setText(_translate("SelectParamByBobyqaDlg", "C1:", None))
        self.label_16.setText(_translate("SelectParamByBobyqaDlg", "~", None))
        self.label_c1_5.setText(_translate("SelectParamByBobyqaDlg", "S1:", None))
        self.label_18.setText(_translate("SelectParamByBobyqaDlg", "~", None))
        self.label_c1_8.setText(_translate("SelectParamByBobyqaDlg", "T1:", None))
        self.label_17.setText(_translate("SelectParamByBobyqaDlg", "~", None))
        self.label_c2range.setText(_translate("SelectParamByBobyqaDlg", "C2:", None))
        self.label_c2dru.setText(_translate("SelectParamByBobyqaDlg", "~", None))
        self.label_s2range.setText(_translate("SelectParamByBobyqaDlg", "S2:", None))
        self.label_s2dru.setText(_translate("SelectParamByBobyqaDlg", "~", None))
        self.label_t2range.setText(_translate("SelectParamByBobyqaDlg", "T2:", None))
        self.label_t2dru.setText(_translate("SelectParamByBobyqaDlg", "~", None))
        self.label_c3range.setText(_translate("SelectParamByBobyqaDlg", "C3:", None))
        self.label_c3dru.setText(_translate("SelectParamByBobyqaDlg", "~", None))
        self.label_s3range.setText(_translate("SelectParamByBobyqaDlg", "S3:", None))
        self.label_s3dru.setText(_translate("SelectParamByBobyqaDlg", "~", None))
        self.label_t3range.setText(_translate("SelectParamByBobyqaDlg", "T3:", None))
        self.label_t3dru.setText(_translate("SelectParamByBobyqaDlg", "~", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SelectParamByBobyqaDlg", "Objecive Function", None))
        self.pushButton_lastfitting.setText(_translate("SelectParamByBobyqaDlg", "Initial Guess From Last Fitting", None))
        self.pushButton_calculate.setText(_translate("SelectParamByBobyqaDlg", "Compute", None))
        self.pushButton_close.setText(_translate("SelectParamByBobyqaDlg", "Close", None))

