# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\scku\Desktop\GitRepos\STARBME\starbme_src\gui\ui\ui_SelectParamByPsoDlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets

def _fromUtf8(s):
    return s

def _translate(context, text, disambig):
    return QtCore.QCoreApplication.translate(context, text)

class Ui_SelectParamByPsoDlg(object):
    def setupUi(self, SelectParamByPsoDlg):
        SelectParamByPsoDlg.setObjectName(_fromUtf8("SelectParamByPsoDlg"))
        SelectParamByPsoDlg.setWindowModality(QtCore.Qt.NonModal)
        SelectParamByPsoDlg.resize(576, 171)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(SelectParamByPsoDlg)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtWidgets.QTabWidget(SelectParamByPsoDlg)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget_1 = QtWidgets.QWidget(self.tab_2)
        self.widget_1.setObjectName(_fromUtf8("widget_1"))
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_1)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_c1_2 = QtWidgets.QLabel(self.widget_1)
        self.label_c1_2.setMinimumSize(QtCore.QSize(16, 0))
        self.label_c1_2.setObjectName(_fromUtf8("label_c1_2"))
        self.horizontalLayout_8.addWidget(self.label_c1_2)
        self.lineEdit_c1small = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_c1small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_c1small.setObjectName(_fromUtf8("lineEdit_c1small"))
        self.horizontalLayout_8.addWidget(self.lineEdit_c1small)
        self.label_16 = QtWidgets.QLabel(self.widget_1)
        self.label_16.setMinimumSize(QtCore.QSize(16, 0))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_8.addWidget(self.label_16)
        self.lineEdit_c1large = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_c1large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_c1large.setObjectName(_fromUtf8("lineEdit_c1large"))
        self.horizontalLayout_8.addWidget(self.lineEdit_c1large)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.label_c1_5 = QtWidgets.QLabel(self.widget_1)
        self.label_c1_5.setMinimumSize(QtCore.QSize(16, 0))
        self.label_c1_5.setObjectName(_fromUtf8("label_c1_5"))
        self.horizontalLayout_8.addWidget(self.label_c1_5)
        self.lineEdit_s1small = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_s1small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_s1small.setObjectName(_fromUtf8("lineEdit_s1small"))
        self.horizontalLayout_8.addWidget(self.lineEdit_s1small)
        self.label_18 = QtWidgets.QLabel(self.widget_1)
        self.label_18.setMinimumSize(QtCore.QSize(16, 0))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_8.addWidget(self.label_18)
        self.lineEdit_s1large = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_s1large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_s1large.setObjectName(_fromUtf8("lineEdit_s1large"))
        self.horizontalLayout_8.addWidget(self.lineEdit_s1large)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.label_c1_8 = QtWidgets.QLabel(self.widget_1)
        self.label_c1_8.setMinimumSize(QtCore.QSize(16, 0))
        self.label_c1_8.setObjectName(_fromUtf8("label_c1_8"))
        self.horizontalLayout_8.addWidget(self.label_c1_8)
        self.lineEdit_t1small = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_t1small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_t1small.setObjectName(_fromUtf8("lineEdit_t1small"))
        self.horizontalLayout_8.addWidget(self.lineEdit_t1small)
        self.label_17 = QtWidgets.QLabel(self.widget_1)
        self.label_17.setMinimumSize(QtCore.QSize(16, 0))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_8.addWidget(self.label_17)
        self.lineEdit_t1large = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_t1large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_t1large.setObjectName(_fromUtf8("lineEdit_t1large"))
        self.horizontalLayout_8.addWidget(self.lineEdit_t1large)
        self.verticalLayout_2.addWidget(self.widget_1)
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setEnabled(True)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_c2range = QtWidgets.QLabel(self.widget_2)
        self.label_c2range.setEnabled(True)
        self.label_c2range.setMinimumSize(QtCore.QSize(16, 0))
        self.label_c2range.setObjectName(_fromUtf8("label_c2range"))
        self.horizontalLayout_9.addWidget(self.label_c2range)
        self.lineEdit_c2small = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_c2small.setEnabled(True)
        self.lineEdit_c2small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_c2small.setObjectName(_fromUtf8("lineEdit_c2small"))
        self.horizontalLayout_9.addWidget(self.lineEdit_c2small)
        self.label_c2dru = QtWidgets.QLabel(self.widget_2)
        self.label_c2dru.setEnabled(True)
        self.label_c2dru.setMinimumSize(QtCore.QSize(16, 0))
        self.label_c2dru.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c2dru.setObjectName(_fromUtf8("label_c2dru"))
        self.horizontalLayout_9.addWidget(self.label_c2dru)
        self.lineEdit_c2large = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_c2large.setEnabled(True)
        self.lineEdit_c2large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_c2large.setObjectName(_fromUtf8("lineEdit_c2large"))
        self.horizontalLayout_9.addWidget(self.lineEdit_c2large)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.label_s2range = QtWidgets.QLabel(self.widget_2)
        self.label_s2range.setEnabled(True)
        self.label_s2range.setMinimumSize(QtCore.QSize(16, 0))
        self.label_s2range.setObjectName(_fromUtf8("label_s2range"))
        self.horizontalLayout_9.addWidget(self.label_s2range)
        self.lineEdit_s2small = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_s2small.setEnabled(True)
        self.lineEdit_s2small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_s2small.setObjectName(_fromUtf8("lineEdit_s2small"))
        self.horizontalLayout_9.addWidget(self.lineEdit_s2small)
        self.label_s2dru = QtWidgets.QLabel(self.widget_2)
        self.label_s2dru.setEnabled(True)
        self.label_s2dru.setMinimumSize(QtCore.QSize(16, 0))
        self.label_s2dru.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s2dru.setObjectName(_fromUtf8("label_s2dru"))
        self.horizontalLayout_9.addWidget(self.label_s2dru)
        self.lineEdit_s2large = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_s2large.setEnabled(True)
        self.lineEdit_s2large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_s2large.setObjectName(_fromUtf8("lineEdit_s2large"))
        self.horizontalLayout_9.addWidget(self.lineEdit_s2large)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.label_t2range = QtWidgets.QLabel(self.widget_2)
        self.label_t2range.setEnabled(True)
        self.label_t2range.setMinimumSize(QtCore.QSize(16, 0))
        self.label_t2range.setObjectName(_fromUtf8("label_t2range"))
        self.horizontalLayout_9.addWidget(self.label_t2range)
        self.lineEdit_t2small = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_t2small.setEnabled(True)
        self.lineEdit_t2small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_t2small.setObjectName(_fromUtf8("lineEdit_t2small"))
        self.horizontalLayout_9.addWidget(self.lineEdit_t2small)
        self.label_t2dru = QtWidgets.QLabel(self.widget_2)
        self.label_t2dru.setEnabled(True)
        self.label_t2dru.setMinimumSize(QtCore.QSize(16, 0))
        self.label_t2dru.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t2dru.setObjectName(_fromUtf8("label_t2dru"))
        self.horizontalLayout_9.addWidget(self.label_t2dru)
        self.lineEdit_t2large = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_t2large.setEnabled(True)
        self.lineEdit_t2large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_t2large.setObjectName(_fromUtf8("lineEdit_t2large"))
        self.horizontalLayout_9.addWidget(self.lineEdit_t2large)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.tab_2)
        self.widget_3.setEnabled(True)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_c3range = QtWidgets.QLabel(self.widget_3)
        self.label_c3range.setEnabled(True)
        self.label_c3range.setMinimumSize(QtCore.QSize(16, 0))
        self.label_c3range.setObjectName(_fromUtf8("label_c3range"))
        self.horizontalLayout_10.addWidget(self.label_c3range)
        self.lineEdit_c3small = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_c3small.setEnabled(True)
        self.lineEdit_c3small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_c3small.setObjectName(_fromUtf8("lineEdit_c3small"))
        self.horizontalLayout_10.addWidget(self.lineEdit_c3small)
        self.label_c3dru = QtWidgets.QLabel(self.widget_3)
        self.label_c3dru.setEnabled(True)
        self.label_c3dru.setMinimumSize(QtCore.QSize(16, 0))
        self.label_c3dru.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c3dru.setObjectName(_fromUtf8("label_c3dru"))
        self.horizontalLayout_10.addWidget(self.label_c3dru)
        self.lineEdit_c3large = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_c3large.setEnabled(True)
        self.lineEdit_c3large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_c3large.setObjectName(_fromUtf8("lineEdit_c3large"))
        self.horizontalLayout_10.addWidget(self.lineEdit_c3large)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.label_s3range = QtWidgets.QLabel(self.widget_3)
        self.label_s3range.setEnabled(True)
        self.label_s3range.setMinimumSize(QtCore.QSize(16, 0))
        self.label_s3range.setObjectName(_fromUtf8("label_s3range"))
        self.horizontalLayout_10.addWidget(self.label_s3range)
        self.lineEdit_s3small = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_s3small.setEnabled(True)
        self.lineEdit_s3small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_s3small.setObjectName(_fromUtf8("lineEdit_s3small"))
        self.horizontalLayout_10.addWidget(self.lineEdit_s3small)
        self.label_s3dru = QtWidgets.QLabel(self.widget_3)
        self.label_s3dru.setEnabled(True)
        self.label_s3dru.setMinimumSize(QtCore.QSize(16, 0))
        self.label_s3dru.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s3dru.setObjectName(_fromUtf8("label_s3dru"))
        self.horizontalLayout_10.addWidget(self.label_s3dru)
        self.lineEdit_s3large = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_s3large.setEnabled(True)
        self.lineEdit_s3large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_s3large.setObjectName(_fromUtf8("lineEdit_s3large"))
        self.horizontalLayout_10.addWidget(self.lineEdit_s3large)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.label_t3range = QtWidgets.QLabel(self.widget_3)
        self.label_t3range.setEnabled(True)
        self.label_t3range.setMinimumSize(QtCore.QSize(16, 0))
        self.label_t3range.setObjectName(_fromUtf8("label_t3range"))
        self.horizontalLayout_10.addWidget(self.label_t3range)
        self.lineEdit_t3small = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_t3small.setEnabled(True)
        self.lineEdit_t3small.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_t3small.setObjectName(_fromUtf8("lineEdit_t3small"))
        self.horizontalLayout_10.addWidget(self.lineEdit_t3small)
        self.label_t3dru = QtWidgets.QLabel(self.widget_3)
        self.label_t3dru.setEnabled(True)
        self.label_t3dru.setMinimumSize(QtCore.QSize(16, 0))
        self.label_t3dru.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t3dru.setObjectName(_fromUtf8("label_t3dru"))
        self.horizontalLayout_10.addWidget(self.label_t3dru)
        self.lineEdit_t3large = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_t3large.setEnabled(True)
        self.lineEdit_t3large.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_t3large.setObjectName(_fromUtf8("lineEdit_t3large"))
        self.horizontalLayout_10.addWidget(self.lineEdit_t3large)
        self.verticalLayout_2.addWidget(self.widget_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMinimumSize(QtCore.QSize(84, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_pn = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_pn.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_pn.setText(_fromUtf8(""))
        self.lineEdit_pn.setObjectName(_fromUtf8("lineEdit_pn"))
        self.horizontalLayout.addWidget(self.lineEdit_pn)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(84, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_ct = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_ct.setText(_fromUtf8(""))
        self.lineEdit_ct.setObjectName(_fromUtf8("lineEdit_ct"))
        self.horizontalLayout.addWidget(self.lineEdit_ct)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setMinimumSize(QtCore.QSize(70, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_iw = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_iw.setText(_fromUtf8(""))
        self.lineEdit_iw.setObjectName(_fromUtf8("lineEdit_iw"))
        self.horizontalLayout_2.addWidget(self.lineEdit_iw)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setMinimumSize(QtCore.QSize(70, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_sc = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_sc.setText(_fromUtf8(""))
        self.lineEdit_sc.setObjectName(_fromUtf8("lineEdit_sc"))
        self.horizontalLayout_2.addWidget(self.lineEdit_sc)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMinimumSize(QtCore.QSize(84, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit_si = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_si.setText(_fromUtf8(""))
        self.lineEdit_si.setObjectName(_fromUtf8("lineEdit_si"))
        self.horizontalLayout_2.addWidget(self.lineEdit_si)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 26, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.pushButton_calculate = QtWidgets.QPushButton(SelectParamByPsoDlg)
        self.pushButton_calculate.setObjectName(_fromUtf8("pushButton_calculate"))
        self.horizontalLayout_6.addWidget(self.pushButton_calculate)
        self.pushButton_close = QtWidgets.QPushButton(SelectParamByPsoDlg)
        self.pushButton_close.setObjectName(_fromUtf8("pushButton_close"))
        self.horizontalLayout_6.addWidget(self.pushButton_close)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)

        self.retranslateUi(SelectParamByPsoDlg)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SelectParamByPsoDlg)

    def retranslateUi(self, SelectParamByPsoDlg):
        SelectParamByPsoDlg.setWindowTitle(_translate("SelectParamByPsoDlg", "Select Parameters By Particle Swarm Optimization", None))
        self.label_c1_2.setText(_translate("SelectParamByPsoDlg", "C1:", None))
        self.label_16.setText(_translate("SelectParamByPsoDlg", "~", None))
        self.label_c1_5.setText(_translate("SelectParamByPsoDlg", "S1:", None))
        self.label_18.setText(_translate("SelectParamByPsoDlg", "~", None))
        self.label_c1_8.setText(_translate("SelectParamByPsoDlg", "T1:", None))
        self.label_17.setText(_translate("SelectParamByPsoDlg", "~", None))
        self.label_c2range.setText(_translate("SelectParamByPsoDlg", "C2:", None))
        self.label_c2dru.setText(_translate("SelectParamByPsoDlg", "~", None))
        self.label_s2range.setText(_translate("SelectParamByPsoDlg", "S2:", None))
        self.label_s2dru.setText(_translate("SelectParamByPsoDlg", "~", None))
        self.label_t2range.setText(_translate("SelectParamByPsoDlg", "T2:", None))
        self.label_t2dru.setText(_translate("SelectParamByPsoDlg", "~", None))
        self.label_c3range.setText(_translate("SelectParamByPsoDlg", "C3:", None))
        self.label_c3dru.setText(_translate("SelectParamByPsoDlg", "~", None))
        self.label_s3range.setText(_translate("SelectParamByPsoDlg", "S3:", None))
        self.label_s3dru.setText(_translate("SelectParamByPsoDlg", "~", None))
        self.label_t3range.setText(_translate("SelectParamByPsoDlg", "T3:", None))
        self.label_t3dru.setText(_translate("SelectParamByPsoDlg", "~", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SelectParamByPsoDlg", "Objective Function", None))
        self.label.setText(_translate("SelectParamByPsoDlg", "Particle Number:", None))
        self.label_2.setText(_translate("SelectParamByPsoDlg", "Compute Times:", None))
        self.label_3.setText(_translate("SelectParamByPsoDlg", "Inertia Weight:", None))
        self.label_4.setText(_translate("SelectParamByPsoDlg", "Self Cognition:", None))
        self.label_5.setText(_translate("SelectParamByPsoDlg", "Social Interaction:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SelectParamByPsoDlg", "PSO Parameters", None))
        self.pushButton_calculate.setText(_translate("SelectParamByPsoDlg", "Compute", None))
        self.pushButton_close.setText(_translate("SelectParamByPsoDlg", "Close", None))

