# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\scku\Desktop\GitRepos\STARBME\starbme_src\gui\ui\ui_SetDataDlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets

def _fromUtf8(s):
    return s

def _translate(context, text, disambig):
    return QtCore.QCoreApplication.translate(context, text)

class Ui_SetDataDlg(object):
    def setupUi(self, SetDataDlg):
        SetDataDlg.setObjectName(_fromUtf8("SetDataDlg"))
        SetDataDlg.setWindowModality(QtCore.Qt.WindowModal)
        SetDataDlg.resize(500, 431)
        SetDataDlg.setMinimumSize(QtCore.QSize(500, 431))
        self.horizontalLayout = QtWidgets.QHBoxLayout(SetDataDlg)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtWidgets.QTabWidget(SetDataDlg)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.comboBox_hardfrom = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_hardfrom.sizePolicy().hasHeightForWidth())
        self.comboBox_hardfrom.setSizePolicy(sizePolicy)
        self.comboBox_hardfrom.setObjectName(_fromUtf8("comboBox_hardfrom"))
        self.comboBox_hardfrom.addItem(_fromUtf8(""))
        self.comboBox_hardfrom.addItem(_fromUtf8(""))
        self.comboBox_hardfrom.addItem(_fromUtf8(""))
        self.comboBox_hardfrom.addItem(_fromUtf8(""))
        self.comboBox_hardfrom.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.comboBox_hardfrom)
        self.pushButton_hardselect = QtWidgets.QPushButton(self.tab)
        self.pushButton_hardselect.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_hardselect.setObjectName(_fromUtf8("pushButton_hardselect"))
        self.horizontalLayout_16.addWidget(self.pushButton_hardselect)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.tableWidget_harddata = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_harddata.setObjectName(_fromUtf8("tableWidget_harddata"))
        self.tableWidget_harddata.setColumnCount(0)
        self.tableWidget_harddata.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_harddata)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox_x = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_x.sizePolicy().hasHeightForWidth())
        self.comboBox_x.setSizePolicy(sizePolicy)
        self.comboBox_x.setEditable(False)
        self.comboBox_x.setFrame(True)
        self.comboBox_x.setObjectName(_fromUtf8("comboBox_x"))
        self.horizontalLayout_2.addWidget(self.comboBox_x)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBox_y = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_y.sizePolicy().hasHeightForWidth())
        self.comboBox_y.setSizePolicy(sizePolicy)
        self.comboBox_y.setObjectName(_fromUtf8("comboBox_y"))
        self.horizontalLayout_2.addWidget(self.comboBox_y)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBox_t = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_t.sizePolicy().hasHeightForWidth())
        self.comboBox_t.setSizePolicy(sizePolicy)
        self.comboBox_t.setObjectName(_fromUtf8("comboBox_t"))
        self.horizontalLayout_3.addWidget(self.comboBox_t)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_6 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.comboBox_z = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_z.sizePolicy().hasHeightForWidth())
        self.comboBox_z.setSizePolicy(sizePolicy)
        self.comboBox_z.setObjectName(_fromUtf8("comboBox_z"))
        self.horizontalLayout_3.addWidget(self.comboBox_z)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_inputformat = QtWidgets.QLabel(self.tab_2)
        self.label_inputformat.setEnabled(True)
        self.label_inputformat.setObjectName(_fromUtf8("label_inputformat"))
        self.horizontalLayout_5.addWidget(self.label_inputformat)
        self.comboBox_inputformat = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_inputformat.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_inputformat.sizePolicy().hasHeightForWidth())
        self.comboBox_inputformat.setSizePolicy(sizePolicy)
        self.comboBox_inputformat.setObjectName(_fromUtf8("comboBox_inputformat"))
        self.comboBox_inputformat.addItem(_fromUtf8(""))
        self.comboBox_inputformat.addItem(_fromUtf8(""))
        self.comboBox_inputformat.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_inputformat)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.label_softpdftype = QtWidgets.QLabel(self.tab_2)
        self.label_softpdftype.setEnabled(True)
        self.label_softpdftype.setMinimumSize(QtCore.QSize(71, 0))
        self.label_softpdftype.setObjectName(_fromUtf8("label_softpdftype"))
        self.horizontalLayout_5.addWidget(self.label_softpdftype)
        self.comboBox_softpdftype = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_softpdftype.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_softpdftype.sizePolicy().hasHeightForWidth())
        self.comboBox_softpdftype.setSizePolicy(sizePolicy)
        self.comboBox_softpdftype.setEditable(False)
        self.comboBox_softpdftype.setFrame(True)
        self.comboBox_softpdftype.setObjectName(_fromUtf8("comboBox_softpdftype"))
        self.comboBox_softpdftype.addItem(_fromUtf8(""))
        self.comboBox_softpdftype.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_softpdftype)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.horizontalLayout_5.addLayout(self.horizontalLayout_15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_17.addWidget(self.label_12)
        self.comboBox_softfrom = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_softfrom.setObjectName(_fromUtf8("comboBox_softfrom"))
        self.comboBox_softfrom.addItem(_fromUtf8(""))
        self.comboBox_softfrom.addItem(_fromUtf8(""))
        self.comboBox_softfrom.addItem(_fromUtf8(""))
        self.horizontalLayout_17.addWidget(self.comboBox_softfrom)
        self.pushButton_softselect = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_softselect.setObjectName(_fromUtf8("pushButton_softselect"))
        self.horizontalLayout_17.addWidget(self.pushButton_softselect)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_2.addWidget(self.line_4)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_datapreview_2 = QtWidgets.QLabel(self.tab_2)
        self.label_datapreview_2.setEnabled(True)
        self.label_datapreview_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_datapreview_2.setObjectName(_fromUtf8("label_datapreview_2"))
        self.horizontalLayout_18.addWidget(self.label_datapreview_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.tableWidget_softdata = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_softdata.setObjectName(_fromUtf8("tableWidget_softdata"))
        self.tableWidget_softdata.setColumnCount(0)
        self.tableWidget_softdata.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget_softdata)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.comboBox_soft_x = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_soft_x.sizePolicy().hasHeightForWidth())
        self.comboBox_soft_x.setSizePolicy(sizePolicy)
        self.comboBox_soft_x.setObjectName(_fromUtf8("comboBox_soft_x"))
        self.horizontalLayout_6.addWidget(self.comboBox_soft_x)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_10.addWidget(self.label)
        self.comboBox_soft_y = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_soft_y.sizePolicy().hasHeightForWidth())
        self.comboBox_soft_y.setSizePolicy(sizePolicy)
        self.comboBox_soft_y.setObjectName(_fromUtf8("comboBox_soft_y"))
        self.horizontalLayout_10.addWidget(self.comboBox_soft_y)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_11.addWidget(self.label_10)
        self.comboBox_soft_t = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_soft_t.sizePolicy().hasHeightForWidth())
        self.comboBox_soft_t.setSizePolicy(sizePolicy)
        self.comboBox_soft_t.setObjectName(_fromUtf8("comboBox_soft_t"))
        self.horizontalLayout_11.addWidget(self.comboBox_soft_t)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_soft_1 = QtWidgets.QLabel(self.tab_2)
        self.label_soft_1.setObjectName(_fromUtf8("label_soft_1"))
        self.horizontalLayout_12.addWidget(self.label_soft_1)
        self.comboBox_soft_1 = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_soft_1.sizePolicy().hasHeightForWidth())
        self.comboBox_soft_1.setSizePolicy(sizePolicy)
        self.comboBox_soft_1.setObjectName(_fromUtf8("comboBox_soft_1"))
        self.horizontalLayout_12.addWidget(self.comboBox_soft_1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_soft_2 = QtWidgets.QLabel(self.tab_2)
        self.label_soft_2.setObjectName(_fromUtf8("label_soft_2"))
        self.horizontalLayout_13.addWidget(self.label_soft_2)
        self.comboBox_soft_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_soft_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_soft_2.sizePolicy().hasHeightForWidth())
        self.comboBox_soft_2.setSizePolicy(sizePolicy)
        self.comboBox_soft_2.setObjectName(_fromUtf8("comboBox_soft_2"))
        self.horizontalLayout_13.addWidget(self.comboBox_soft_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_soft_3 = QtWidgets.QLabel(self.tab_2)
        self.label_soft_3.setObjectName(_fromUtf8("label_soft_3"))
        self.horizontalLayout_14.addWidget(self.label_soft_3)
        self.comboBox_soft_3 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_soft_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_soft_3.sizePolicy().hasHeightForWidth())
        self.comboBox_soft_3.setSizePolicy(sizePolicy)
        self.comboBox_soft_3.setObjectName(_fromUtf8("comboBox_soft_3"))
        self.horizontalLayout_14.addWidget(self.comboBox_soft_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.line = QtWidgets.QFrame(SetDataDlg)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_create = QtWidgets.QPushButton(SetDataDlg)
        self.pushButton_create.setObjectName(_fromUtf8("pushButton_create"))
        self.verticalLayout_3.addWidget(self.pushButton_create)
        self.pushButton_cancel = QtWidgets.QPushButton(SetDataDlg)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.verticalLayout_3.addWidget(self.pushButton_cancel)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(SetDataDlg)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_x.setCurrentIndex(-1)
        self.comboBox_softpdftype.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SetDataDlg)

    def retranslateUi(self, SetDataDlg):
        SetDataDlg.setWindowTitle(_translate("SetDataDlg", "Specify Data", None))
        self.label_11.setText(_translate("SetDataDlg", "Select Hard Data Source From:", None))
        self.comboBox_hardfrom.setItemText(0, _translate("SetDataDlg", "File", None))
        self.comboBox_hardfrom.setItemText(1, _translate("SetDataDlg", "Layer", None))
        self.comboBox_hardfrom.setItemText(2, _translate("SetDataDlg", "Shape File", None))
        self.comboBox_hardfrom.setItemText(3, _translate("SetDataDlg", "Shape File (With Time Input)", None))
        self.comboBox_hardfrom.setItemText(4, _translate("SetDataDlg", "Grid Input", None))
        self.pushButton_hardselect.setText(_translate("SetDataDlg", "Select...", None))
        self.label_2.setText(_translate("SetDataDlg", "----Hard Data Preview----", None))
        self.label_3.setText(_translate("SetDataDlg", "X:", None))
        self.label_4.setText(_translate("SetDataDlg", "Y:", None))
        self.label_5.setText(_translate("SetDataDlg", "T:", None))
        self.label_6.setText(_translate("SetDataDlg", "Z:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SetDataDlg", "Hard Data", None))
        self.label_inputformat.setText(_translate("SetDataDlg", "Soft PDF Type", None))
        self.comboBox_inputformat.setItemText(0, _translate("SetDataDlg", "User Defined", None))
        self.comboBox_inputformat.setItemText(1, _translate("SetDataDlg", "Gaussian", None))
        self.comboBox_inputformat.setItemText(2, _translate("SetDataDlg", "Uniform", None))
        self.label_softpdftype.setText(_translate("SetDataDlg", "Soft PDF Form:", None))
        self.comboBox_softpdftype.setItemText(0, _translate("SetDataDlg", "Histogram", None))
        self.comboBox_softpdftype.setItemText(1, _translate("SetDataDlg", "Linear", None))
        self.label_12.setText(_translate("SetDataDlg", "Select Soft Data Source From:", None))
        self.comboBox_softfrom.setItemText(0, _translate("SetDataDlg", "File", None))
        self.comboBox_softfrom.setItemText(1, _translate("SetDataDlg", "Layer", None))
        self.comboBox_softfrom.setItemText(2, _translate("SetDataDlg", "Shape File", None))
        self.pushButton_softselect.setText(_translate("SetDataDlg", "Select...", None))
        self.label_datapreview_2.setText(_translate("SetDataDlg", "----Soft Data Preview----", None))
        self.label_7.setText(_translate("SetDataDlg", "X:", None))
        self.label.setText(_translate("SetDataDlg", "Y:", None))
        self.label_10.setText(_translate("SetDataDlg", "T:", None))
        self.label_soft_1.setText(_translate("SetDataDlg", "Number of Limits:", None))
        self.label_soft_2.setText(_translate("SetDataDlg", "Limits:", None))
        self.label_soft_3.setText(_translate("SetDataDlg", "Probadens:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SetDataDlg", "Soft Data", None))
        self.pushButton_create.setText(_translate("SetDataDlg", "Create", None))
        self.pushButton_cancel.setText(_translate("SetDataDlg", "Cancel", None))

